application/backend/views/category/category-form.php, application/backend/views/product/product-form.php
for proper behaviour with many category groups. this should close #154
=> add category_group_id to preview url

application/migrations/m150209_225849_dynamic_content_default_block.php, application/migrations/m150216_121527_deleting_append_fields_in_DC.php
If add tablePrefix, these migrations broken installation.
=> Change dynamic_content on {{%dynamic_content}}

application/models/Category.php
Предлагаю добавить в селект из базы поле `category_group_id`, которое используется ниже в Url::to()
=> Добавление к функции формирования меню

application/widgets/form/js/ajax-form.js
That's how we should use client side validating and ajax submitting form to prevent double submitting.
=> Prevent double submitting

application/modules/core/helpers/ContentBlockHelper.php
And besides that we can now easier implement method like compileFormChunk, define for example the '*' token for this.
=> This fix will be correct.

application/modules/core/controllers/BackendChunkController.php, application/modules/core/helpers/ContentBlockHelper.php, application/modules/core/views/backend-chunk/edit.php
Using BackendRedirects, Buttons Helper
Formatter tested on next cases:
[[+param:asdate, dd:m:YY ]] [[+param:asemail]] [[+param:asdecimal, 3]] [[+param:asboolean]] [[+param:ascurrency, usd]]
=> content blocks

README.md
=> update php version in readme

application/messages/ru/app.php, application/modules/image/widgets/ImageDropzone.php
Fix crash backend if image not exists and show error.
=> fix crash backend if image not exists

application/modules/seo/behaviors/MetaBehavior.php
the way it is now - it simply doesn't work
=> make it work =)

application/backend/views/properties/edit-static-value-form.php, application/messages/ru/app.php, application/migrations/m151218_203419_property_title_prepend.php, application/models/PropertyStaticValues.php, application/modules/shop/controllers/ProductController.php, application/properties/url/PropertyPart.php
Теперь для title на страницах фильтров, можно добавлять части заголовка и в начало title
=> Расширение возможностей базовых генераций

application/commands/data/layout.tmpl, application/modules/core/CoreModule.php, application/modules/core/models/ConfigConfigurationModel.php, application/modules/core/views/configurable/_config.php, application/modules/installer/commands/InstallController.php, application/modules/installer/components/InstallerHelper.php, application/modules/installer/controllers/InstallerController.php, application/modules/installer/models/FinalStep.php, application/modules/installer/views/installer/final.php, application/modules/page/components/PageRule.php, application/modules/page/models/Page.php, application/modules/review/views/review-email-template.php, application/modules/seo/controllers/SitemapController.php, application/modules/shop/views/layouts/print.php, application/properties/handlers/fileInput/views/backend-render.php, application/views/layouts/blocks/header.php
Уважаем порт как надо. fixes #271
=> respect server port properly

application/extensions/demo/migrations/m150605_094805_demo_data.php
=> Progress bar for demo files download.

application/backend/actions/JSSelectableTreeGetTree.php
Добавление сортировки в дерево категорий на странице редактирования продукта
=> adding order into cat. tree on the backend product page

application/widgets/form/views/form.php
=> [hot fix] bring the capcha back

application/.gitignore, application/components/payment/RobokassaPayment.php, application/installed.mark
I this this issue may occur and in other payment method.
When we trying to pay with this payment type it's must redirect us to other website here:
```
$SignatureValue = $this->getSignature();
$data['SignatureValue'] = $SignatureValue;
$url = 'http://' . $this->merchantUrl . '/Index.aspx?' . http_build_query($data);
return $this->redirect($url);
}
```
And in `pay` view we have this
```
echo $paymentType->getPayment($order, $orderTransaction)->content();
```
In this case we will get typecasting error when we try to echo redirect.
=> Issue with Robokassa

application/modules/shop/widgets/views/order-chat/backend.php
=> Fixes #243.

application/modules/shop/assets/js/batch-edit-price.js
Добавил обновление текущей страницы после закрытия окна с результатами обновления цен
=> refreshing of current page after closing information window

application/extensions/DefaultTheme/widgets/CategoriesList/ConfigurationModel.php, application/extensions/DefaultTheme/widgets/CategoriesList/Widget.php, application/extensions/DefaultTheme/widgets/CategoriesList/views/_config.php, application/extensions/DefaultTheme/widgets/CategoriesList/views/categories-list.php, application/widgets/PlainCategoriesWidget.php, application/widgets/views/categories-list.php
=> Fix PlainCategoriesWidget

application/migrations/m160714_114125_warning_set_unique_static_value_key.php
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by
=> fix migrate on mysql 5.7

application/modules/shop/models/ShippingDiscount.php
Переменная $order не проверяется перед использованием
=> Checking $order variable before using

application/migrations/m151103_105905_shipping_discount.php
> create table shipping_discount ... done (time: 0.078s)
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: app\modules\shop\models\DiscountType::custom_view'
`custom_view` field added by `m170408_060716_disctype_add_customview.php` migration (after `m151103_105905_shipping_discount`).
`DiscountType` model has validation rule for `custom_view` field. 
`m151103_105905_shipping_discount` -> `$discountType->save()` - runs validation for not exists field.
=> Fix migration error

application/modules/shop/models/Category.php
без этого импорт категорий не работает  в принципе т.к. базовые атрибуты модели ничем и никем не заполняются
=> sembalance of working import

application/modules/seo/controllers/ManageController.php, application/modules/seo/models/Counter.php, application/modules/seo/views/manage/_counterGrid.php
Rework of seo/manage/counter table:
* DynaGrid instead of GridView
* remove editor from table
* add editable and filtrable counter position
also closes #360
=> Rework of seo/manage/counter table

application/backend/views/properties/edit-property.php
closes #336
Tabs:
* static values (if any) - first and active tab. if none present - hide this tab
* core params (if non static values present - first and active tab)
* logic params
* image
=> introduce tabs at backend/edit-property

application/modules/data/commands/FileController.php, application/modules/data/components/DummyDHProcessor.php, application/modules/data/components/Import.php, application/modules/data/components/ImportModelAUnserializeEvent.php, application/modules/data/components/ImportModelBUnserializeEvent.php, application/modules/data/components/ImportModelLoadEvent.php, application/modules/data/models/ImportModel.php, application/modules/image/widgets/ImageDropzone.php
Examples: for process custom price list xlsx and/or customizing order item of fields/properties
=> Add ability to customizing import/export process
